# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Cache@2
    displayName: Cache node_modules
    inputs:
      key: 'npm | “$(Agent.OS)” | $(Build.SourcesDirectory)/package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: '$(Build.SourcesDirectory)/node_modules'

  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '16.x'

  - script: |
      npm install -g @angular/cli
      npm install
    displayName: 'Install modules'

  - script: |
      npm run lint
    displayName: 'Lint'

  - script: |
      ng build --prod
    displayName: 'Build'
